<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.yoxel.aurinko</groupId>
	<artifactId>aurinko-service</artifactId>
	<version>1.8.12-SNAPSHOT</version>

	<parent>
		<groupId>com.yoxel</groupId>
		<artifactId>parent</artifactId>
		<version>1.7.3-j25-SNAPSHOT</version>
	</parent>

	<properties>
		<lombok.version>1.18.40</lombok.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.yoxel.model2</groupId>
			<artifactId>model2</artifactId>
			<version>4.3.4-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.yoxel</groupId>
			<artifactId>oauth-flow</artifactId>
			<version>1.6.2</version>
		</dependency>

		<dependency>
			<groupId>com.google.http-client</groupId>
			<artifactId>google-http-client-apache-v2</artifactId>
			<version>1.39.2</version>
		</dependency>

		<dependency>
			<groupId>com.yoxel</groupId>
			<artifactId>yoxel-commons</artifactId>
			<version>0.3</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jul-to-slf4j</artifactId>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
