package com.yoxel.commons.xstream;

import java.util.Collection;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

/**
 * Utility methods for creating standard Java streams.
 *
 * @author leopold
 * @since 1/09/17
 */
public final class Streams {

  private Streams() {
  }

  public static <T> Stream<T> iterateWhile(T seed, Function<T, T> generate,
      Predicate<T> generateWhile) {
    return iterate(seed, generate, generateWhile.negate(), false);
  }

  public static <T> Stream<T> iterateUntil(T seed, Function<T, T> generate,
      Predicate<T> stopWhen) {
    return iterate(seed, generate, stopWhen, true);
  }

  /**
   * Generate a stream of values, where each element is generated by provided function {@code generate}. When an element
   * that satisfies {@code stopWhen} is produced, the generation will stop. {@code includeLast} specifies whether to
   * include this stopper element into the stream.
   */
  public static <T> Stream<T> iterate(T seed, Function<T, T> generate, Predicate<T> stopWhen, boolean includeLast) {

    final Iterator<T> it = new Iterator<T>() {
      private T prev;
      private T next = seed;
      private boolean exhausted = false;

      @Override
      public boolean hasNext() {
        if (exhausted) {
          return false;
        }

        // 1. Check if the PREVIOUS element was the terminator (includeLast = true case)
        if (prev != null && stopWhen.test(prev)) {
          exhausted = true;
          return false;
        }

        // 2. Generate if we don't have a value cached
        if (next == null) {
          next = generate.apply(prev);
        }

        // 3. Check if the CURRENT element is the terminator (includeLast = false case)
        if (!includeLast && next != null && stopWhen.test(next)) {
          next = null;
          exhausted = true;
        }

        return next != null;
      }

      @Override
      public T next() {
        if (!hasNext()) {
          throw new NoSuchElementException();
        }

        prev = next;
        next = null;
        return prev;
      }
    };

    return fromIterator(it);
  }

  /**
   * Create a sequential (non-parallel) Stream from Iterator.
   */
  public static <T> Stream<T> fromIterator(Iterator<T> it) {
    return StreamSupport.stream(((Iterable<T>) () -> it).spliterator(), false);
  }

  /**
   * Generate a stream by sequentially applying functions from {@code functions} list to a value, that is obtained at
   * previous step, starting from {@code seed} value.
   */
  public static <T> Stream<T> expandAll(
      T seed,
      Collection<Function<T, ? extends Collection<T>>> functions) {
    return fromIterator(
        new Iterator<T>() {
          private final Iterator<Function<T, ? extends Collection<T>>> genIt = functions.iterator();
          private Iterator<T> sndLevelIterator;
          private T state = seed;

          @Override
          public boolean hasNext() {
            if (sndLevelIterator != null && sndLevelIterator.hasNext()) {
              return true;
            }

            while (genIt.hasNext()) {

              sndLevelIterator = genIt.next().apply(state).iterator();
              if (sndLevelIterator.hasNext()) {
                return true;
              }
            }
            return false;
          }

          @Override
          public T next() {
            state = sndLevelIterator.next();
            return state;
          }
        }
    );
  }
}
